# Generated by Django 3.2.16 on 2023-01-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
